apiVersion: v1
kind: Service
metadata:
  name: wiki-service
  namespace: tomsther
  labels:
    app: wiki-label
spec:
  type: ClusterIP
  selector:
    app: wiki-label
  ports:
    - name: wiki-port
      protocol: TCP
      port: 80
      targetPort: 3000
